# --- DB CONNECTION ---
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# --- ORM/JPA SETTINGS ---
spring.jpa.show-sql=${DB_SHOW_SQL}
spring.jpa.hibernate.ddl-auto=${DB_DDL_AUTO}
spring.jpa.properties.hibernate.dialect=${DB_DIALECT}
spring.jpa.properties.hibernate.format_sql=${DB_FORMAT_SQL}
